apiVersion: v1
kind: Service
metadata:
  name: campus-complaint-hub-service
  labels:
    app: campus-complaint-hub
spec:
  type: NodePort
  selector:
    app: campus-complaint-hub
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080